import type { ResolucaoDeclarativa } from "../../contracts/pedagogySteps";
import { Evidencia } from "../../constants/evidencias";
import type { MasteryRule,Option,Question } from "../../types";
import type { FichaCompetencia } from "../schema";
export const FracaoEquivalenteMisconception={MAIS_PARTES_MAIS_QUANTIDADE:"mais-partes-mais-quantidade",COMPARA_SO_DENOMINADOR:"compara-so-denominador",MULTIPLICA_SO_UM:"multiplica-so-um"} as const;
export type FracaoEquivalenteMisconceptionTag=typeof FracaoEquivalenteMisconception[keyof typeof FracaoEquivalenteMisconception];
export type FracaoEquivalenteModo="equivalencia-sobreposta"|"equivalencia-lado-a-lado"|"mesmo-denominador"|"mesmo-numerador"|"denominadores-diferentes";
export interface FracaoVisual{numerador:number;denominador:number}
export interface FracaoEquivalenteF73Spec{nivel:number;modo:FracaoEquivalenteModo;esquerda:FracaoVisual;direita:FracaoVisual;resposta:"igual"|"esquerda"|"direita";opcoes:Array<{value:string;label:string;misconception?:FracaoEquivalenteMisconceptionTag}>}
interface Show{esquerda:FracaoVisual;direita:FracaoVisual;sobrepor?:boolean}
const clamp=(n:number)=>Math.max(1,Math.min(5,Math.round(n))); function escolher<T>(xs:T[],rng:()=>number):T{const raw=rng(),n=Number.isFinite(raw)?Math.max(0,Math.min(.999999,raw)):0;return xs[Math.floor(n*xs.length)]??xs[0]}; const txt=(f:FracaoVisual)=>`${f.numerador}/${f.denominador}`;
function comparar(a:FracaoVisual,b:FracaoVisual):"igual"|"esquerda"|"direita"{const d=a.numerador*b.denominador-b.numerador*a.denominador;return d===0?"igual":d>0?"esquerda":"direita"}
function alternativas(a:FracaoVisual,b:FracaoVisual,resposta:FracaoEquivalenteF73Spec["resposta"],tag:FracaoEquivalenteMisconceptionTag){const labels={igual:"São iguais",esquerda:`${txt(a)} é maior`,direita:`${txt(b)} é maior`};return(["igual","esquerda","direita"] as const).map(value=>({value,label:labels[value],...(value===resposta?{}:{misconception:tag})}))}
export function construirFracaoEquivalenteSpec(level:number,rng:()=>number=Math.random):FracaoEquivalenteF73Spec{const nivel=clamp(level);let modo:FracaoEquivalenteModo,esquerda:FracaoVisual,direita:FracaoVisual,tag:FracaoEquivalenteMisconceptionTag;if(nivel<=2){const p=escolher([[{numerador:1,denominador:2},{numerador:2,denominador:4}],[{numerador:1,denominador:3},{numerador:2,denominador:6}],[{numerador:2,denominador:3},{numerador:4,denominador:6}]] as const,rng);esquerda={...p[0]};direita={...p[1]};modo=nivel===1?"equivalencia-sobreposta":"equivalencia-lado-a-lado";tag=FracaoEquivalenteMisconception.MULTIPLICA_SO_UM}else if(nivel===3){const d=escolher([4,5,6],rng);esquerda={numerador:1,denominador:d};direita={numerador:d-1,denominador:d};modo="mesmo-denominador";tag=FracaoEquivalenteMisconception.COMPARA_SO_DENOMINADOR}else if(nivel===4){const n=escolher([1,2],rng),ds=escolher([[3,5],[4,6],[5,8]] as const,rng);esquerda={numerador:n,denominador:ds[0]};direita={numerador:n,denominador:ds[1]};modo="mesmo-numerador";tag=FracaoEquivalenteMisconception.MAIS_PARTES_MAIS_QUANTIDADE}else{const p=escolher([[{numerador:2,denominador:3},{numerador:3,denominador:5}],[{numerador:3,denominador:4},{numerador:5,denominador:8}],[{numerador:2,denominador:5},{numerador:3,denominador:7}]] as const,rng);esquerda={...p[0]};direita={...p[1]};modo="denominadores-diferentes";tag=FracaoEquivalenteMisconception.COMPARA_SO_DENOMINADOR}const resposta=comparar(esquerda,direita);return{nivel,modo,esquerda,direita,resposta,opcoes:alternativas(esquerda,direita,resposta,tag)}}
export function construirFracaoEquivalenteResolucao(spec:FracaoEquivalenteF73Spec):ResolucaoDeclarativa<Show,string,FracaoEquivalenteMisconceptionTag>{return{estadoInicial:{esquerda:spec.esquerda,direita:spec.direita},passos:[{id:"mesmo-inteiro",say:"As barras têm o mesmo comprimento: o inteiro é o mesmo.",show:{esquerda:spec.esquerda,direita:spec.direita},corrige:[FracaoEquivalenteMisconception.MAIS_PARTES_MAIS_QUANTIDADE],parcial:"mesmo-inteiro"},{id:"comparar-espaco",say:spec.resposta==="igual"?"As regiões pintadas ocupam o mesmo espaço.":"Compare o espaço pintado, não o denominador.",show:{esquerda:spec.esquerda,direita:spec.direita,sobrepor:true},corrige:[FracaoEquivalenteMisconception.COMPARA_SO_DENOMINADOR,FracaoEquivalenteMisconception.MULTIPLICA_SO_UM],parcial:spec.resposta}],fallback:0}}
function mastery(f:FichaCompetencia,n:number):MasteryRule{const id=f.niveis?.[n]?.micro,m=f.micros.find(x=>x.id===id);if(!m)throw new Error(`N5.03 sem micro L${n}`);return{acertos:m.dominio.acertos,de:m.dominio.de,sessoes:m.dominio.sessoes}}
export function construirFracaoEquivalenteQuestion(ficha:FichaCompetencia,level:number):Question{if(ficha.id!=="N5.03")throw new Error(`fracaoEquivalenteContract recebeu ${ficha.id}`);const spec=construirFracaoEquivalenteSpec(level),prompt=spec.nivel<=2?"As duas frações representam a mesma quantidade?":"Qual barra representa a maior fração?",options:Option[]=spec.opcoes;return{kind:"fracoes-equivalentes-f73",prompt,audioPrompt:prompt,howto:ficha.howto,explain:ficha.explain,resolucao:construirFracaoEquivalenteResolucao(spec),masteryRule:mastery(ficha,spec.nivel),exigeEvidencia:Evidencia.FRACAO_MESMO_NUMERADOR,uiProps:spec,options,answer:spec.resposta,evaluate:a=>String(a)===spec.resposta}}
